### ISSUE TITLE
TypeScript issues with createSelector

### ISSUE THREAD

**Issue by edolix** [reduxjs/reselect#554] opened 2021-11-18 11:43 UTC
Hello, i'm having an issue with TS and `createSelector`. I was reading the latest release notes for [v4.1.3](https://github.com/reduxjs/reselect/releases/tag/v4.1.3) and [v4.1.4](https://github.com/reduxjs/reselect/releases/tag/v4.1.4) but i wasn't able to find a fix/workaround.

Here's a demo to reproduce the issue: https://stackblitz.com/edit/typescript-vf7zff?file=index.ts

The problem seems related to selectors from `createSelector` with just one additional argument (`complexOne` in the demo). Maybe i'm using the "input selectors" in the wrong way but, looking at the notes in [v4.1.3](https://github.com/reduxjs/reselect/releases/tag/v4.1.3), they should be fine.

Here the code for future reference:

```ts
import { createSelector } from 'reselect';

interface State {
  foo: string;
  bar: number;
}

const initialState: State = {
  foo: 'This is Foo',
  bar: 1,
};

const getFoo = (state: State) => {
  return state.foo;
};
console.log('getFoo:', getFoo(initialState));

const getBar = (state: State) => {
  return state.bar;
};
console.log('getBar:', getBar(initialState));

const simple = createSelector(getFoo, getBar, (foo, bar) => {
  return `${foo} => ${bar}`;
});
console.log('Simple:', simple(initialState));

// Input selectors with positional args
const firstInput = (_: State, first: string) => first;
// Skip the first arg and return only the second.
const secondInput = (_: State, _first: string, second: number) => second;

const complexOne = createSelector(
  getFoo,
  getBar,
  firstInput,
  (foo, bar, first) => {
    return `${foo} => ${bar} || ${first}`;
  }
);
console.log('Complex:', complexOne(initialState, 'first'));

const complexTwo = createSelector(
  getFoo,
  getBar,
  firstInput,
  secondInput,
  (foo, bar, first, second) => {
    return `${foo} => ${bar} || ${first} and ${second}`;
  }
);
// TS should complain since 'second' should be `number`
console.log('Complex:', complexTwo(initialState, 'first', 'second'));
```

#### Versions

TS: 4.5.2
Reselect: 4.1.4

Thank you so much! 

Ref: https://github.com/microsoft/TypeScript/issues/45147
Ref: https://github.com/reduxjs/reselect/issues/459

**Comment by cbbgbw** [comment] 2021-11-18 13:27
For my last version of typescript which does work with reselect is 4.2.1-rc. Maybe it will help.

**Comment by lg-kialo** [comment] 2021-11-18 14:07
I think I'm running into the same issue, here's a minimal reproducing example which does not make much sense but illustrates the issue:
```ts
import { createSelector } from 'reselect';

interface State {
    counter1: number;
    counter2: number;
}

const selectTest = createSelector(
    (state: State, numberA?: number) => numberA,
    (state: State) => state.counter2,
    (numberA, counter2) => numberA ? numberA + counter2 : counter2
);
```

Generated signature:
```ts
const selectTest: ((state: {
    counter1: number;
    counter2: number;
}, params_0?: {}) => number) & OutputSelectorFields<(args_0: number | undefined, args_1: number) => number & {
    clearCache: () => void;
}> & {
    clearCache: () => void;
}
```

The issue is with `params_0?: {}` which is wrong, it should be `params_0?: number` as far as I understand.

**Comment by markerikson** [comment] 2021-11-18 17:27
First question, as per #550: do you have `strictNullChecks: true` in your `tsconfig.json`?

**Comment by lg-kialo** [comment] 2021-11-18 17:41
> strictNullChecks

Actually, no. Thanks for the input

**Comment by markerikson** [comment] 2021-11-18 17:49
Hmm. I'll try to investigate in the next couple days, although tbh I've spent so much time on reworking these types in the last couple weeks that my brain is kinda fried :)

@lg-kialo if you could provide an actual project repro that would be helpful in trying to debug this.

**Comment by lg-kialo** [comment] 2021-11-18 18:00
> Hmm. I'll try to investigate in the next couple days, although tbh I've spent so much time on reworking these types in the last couple weeks that my brain is kinda fried :)
> 
> @lg-kialo if you could provide an actual project repro that would be helpful in trying to debug this.

Here's a codesandbox which shows the problem: https://codesandbox.io/s/nifty-pascal-0d4kj?file=/src/index.ts

**Comment by edolix** [comment] 2021-11-18 18:12
> First question, as per #550: do you have `strictNullChecks: true` in your `tsconfig.json`?

@markerikson Thanks for the input! I'll try it and drop an update here 👍

**Comment by guy-st** [comment] 2021-11-23 20:20
I've reverted to 4.1.0 to have selectors return types working again

**Comment by markerikson** [comment] 2021-11-23 20:25
@guy-st can you provide any additional example projects that show these errors happening? and do you have `strictNullChecks` or `strict` turned on?

**Comment by RoXuS** [comment] 2021-11-23 20:26
Same issue here on 4.1.4.

No issue on 4.0.0.

```
"strict": true,
```

**Comment by markerikson** [comment] 2021-11-23 20:39
Folks, right now I _cannot replicate this_ with our typetests. What I really need are **more example projects that actually show this problem happening**, not just "it fails for me too".

**Comment by RoXuS** [comment] 2021-11-23 21:00
If you edit this sandbox https://codesandbox.io/embed/frosty-violet-ebpxc?fontsize=14&hidenavigation=1&theme=dark

You will get the error:
![image](https://user-images.githubusercontent.com/3296671/143120882-d801a040-b41f-47ba-b141-cb074824ec4d.png)

And if you change the dependencies to 4.0.0 the error gone:

![image](https://user-images.githubusercontent.com/3296671/143121765-195e6da3-3033-4656-9820-69ba56796ad9.png)

**Comment by markerikson** [comment] 2021-11-23 21:02
@RoXuS with the types in 4.1+, you **should not be supplying generic arguments**. `createSelector` _should_ be inferring these automatically.

Does it work okay if you just delete the entire `< >` section?

**Comment by RoXuS** [comment] 2021-11-23 21:11
yes it works! Thx, sorry for disturbance!

**Comment by guy-st** [comment] 2021-11-23 23:28
@markerikson  it is working now with 4.1.4, I can't reproduce either. 
Perhaps it was a matter of "reloading the window" in VSCode after installing `react-use`.
I am using the ["JavaScript and TypeScript Nightly"](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension in VSCode, perhaps it was related.

No, I didn't have strictNullChecks or strict on.

**Comment by markerikson** [comment] 2021-11-23 23:48
That's another good question.  

**Are these errors _solely_ in VS Code, or are they happening at compile time too?**

**Comment by dobernike** [comment] 2021-11-24 07:29
the same issue.



> That's another good question.
> 
> **Are these errors _solely_ in VS Code, or are they happening at compile time too?**


The same issue.

With compile too (webpack 5) and in webstorm

(ts 4.4, yarn modern, reselect ^4.0.0) reproduced

but on ~4.0.0 works fine

**Comment by markerikson** [comment] 2021-11-24 17:54
@edolix : fwiw I see that there is indeed an error in the StackBlitz project, but if I download it and both compile with `tsc` and open it in VS Code, it compiles clean with no errors. Similarly, copying the code into Reselect's typetests file appears to work correctly.

**Comment by edolix** [comment] 2021-11-24 18:18
@markerikson the StackBlitz project shows the errors if you disable the `strict` mode. The issue seems fixed using strict: true.

**Comment by markerikson** [comment] 2021-11-24 18:21
@edolix then that's exactly the problem. As discussed in #550 , **Reselect _needs_ TS to have `strict: true` enabled in order to work right**.

**Comment by markerikson** [comment] 2021-11-24 21:31
Just released https://github.com/reduxjs/reselect/releases/tag/v4.1.5 , which _should_ address additional problems around `undefined` or optional parameters, and all the code samples provided in this issue appear to type-check correctly.

Going to close this issue - if there's any further problems, please open up a new issue, **include a reproduction of the problem and ensure you have `strict: true` enabled**.

**Closed by markerikson** 2021-11-24 21:31 UTC
